name: Build Re:VIEW to make distribution file
# The workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # uses v3 Stable version
    # https://github.com/actions/checkout
    - name: checkout source
      uses: actions/checkout@v3
      with:
        repository: techbookfest-LettuceYogurt/techbookfest17
        token: ${{ secrets.PAT }}
    - uses: docker://vvakame/review:5.8
      with:
        entrypoint: bash
        args: -c "cd articles; rake pdf"
    - uses: actions/upload-artifact@v3
      with:
        name: build book
        path: articles/ReVIEW-Template.pdf
